---
 - hosts: localhost
   tasks:
     - name: install python-pip
       apt:
         name: python-pip
         state: latest
     - name: install docker compose
       pip:
         name: docker-compose
         state: latest
     - name: install git
       apt:
         name: git
         state: latest

